# DX 601 Week 10 Homework

## Introduction

In this homework, you will practice basic operations with matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [3]:
import math
import sys

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the trace of the matrix
\begin{bmatrix}
1 & 5 & 2 \\
-7 & 9 & 8 \\
3 & 2 & 6 \\
\end{bmatrix}


In [8]:
# YOUR CHANGES HERE

arr = np.array([[1, 5, 2],
                [-7, 9, 8],
                [3, 2, 6]])

p1 = np.trace(arr)

In [9]:
p1

np.int64(16)

### Problem 2

Set `p2` to the transpose of the matrix

\begin{bmatrix}
4 & 2 & 7 \\
8 & 5 & 1 \\
2 & 6 & 3 \\
\end{bmatrix}


In [10]:
# YOUR CHANGES HERE

arr = np.array([[4, 2, 7],
                [8, 5, 1],
                [2, 6, 3]])

p2 = np.transpose(arr)

In [11]:
p2

array([[4, 8, 2],
       [2, 5, 6],
       [7, 1, 3]])

### Problem 3

Set `p3` to be the transpose of `q3`.


In [12]:
# DO NOT CHANGE

q3 = np.array([[-0.01360112, -1.46500812, -0.27692561, -0.42310394, -1.08916478],
       [-0.92981147, -1.33763129, -0.60155956,  1.20761548,  0.84523834],
       [-0.7357686 , -0.17268799,  0.88596177, -0.98521575, -1.15429029],
       [-0.98100767, -0.16181207,  0.52053393,  0.74956931, -2.0668364 ],
       [-0.55031032, -0.96781023,  0.2562466 ,  1.05642169, -0.48648003]])
q3

array([[-0.01360112, -1.46500812, -0.27692561, -0.42310394, -1.08916478],
       [-0.92981147, -1.33763129, -0.60155956,  1.20761548,  0.84523834],
       [-0.7357686 , -0.17268799,  0.88596177, -0.98521575, -1.15429029],
       [-0.98100767, -0.16181207,  0.52053393,  0.74956931, -2.0668364 ],
       [-0.55031032, -0.96781023,  0.2562466 ,  1.05642169, -0.48648003]])

Hint: NumPy has a few ways to do this trivially.
You can look them up faster than typing in this matrix or its transpose.

In [13]:
# YOUR CHANGES HERE

p3 = np.transpose(q3)

In [14]:
p3

array([[-0.01360112, -0.92981147, -0.7357686 , -0.98100767, -0.55031032],
       [-1.46500812, -1.33763129, -0.17268799, -0.16181207, -0.96781023],
       [-0.27692561, -0.60155956,  0.88596177,  0.52053393,  0.2562466 ],
       [-0.42310394,  1.20761548, -0.98521575,  0.74956931,  1.05642169],
       [-1.08916478,  0.84523834, -1.15429029, -2.0668364 , -0.48648003]])

### Problem 4

Write a function `p4` that returns `True` if an input matrix is symmetric and `False` otherwise.

Hint: NumPy has a function [`np.array_equal`](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html) that will make this easier.

In [19]:
# YOUR CHANGES HERE

def p4(m):
    arr_transpose = np.transpose(m)
    return np.array_equal(m, arr_transpose)

In [20]:
# should return true
p4(np.array([[1, 0], [0, 1]]))

True

In [21]:
# should return false
p4(np.array([[1, 2], [3, 4]]))

False

### Problem 5

Set `p5` to $3x + 2y$ where $x$ and $y$ are respectively in `x5` and `y5`.


In [24]:
# DO NOT CHANGE

x5 = np.array([[-0.24389677, -0.26830261, -0.9870142 ,  1.23274779,  0.00824161],
       [ 0.33685162,  0.50438823,  0.50953501,  1.06299757,  0.47553274],
       [-0.06979652,  0.88705427,  0.06441108, -0.36479521,  2.14335222],
       [ 0.20775683,  0.96549669,  0.89559484,  1.36015926,  0.21595356],
       [ 1.42545495,  1.1969253 ,  0.84640923,  1.79356692, -1.83408336]])
x5

array([[-0.24389677, -0.26830261, -0.9870142 ,  1.23274779,  0.00824161],
       [ 0.33685162,  0.50438823,  0.50953501,  1.06299757,  0.47553274],
       [-0.06979652,  0.88705427,  0.06441108, -0.36479521,  2.14335222],
       [ 0.20775683,  0.96549669,  0.89559484,  1.36015926,  0.21595356],
       [ 1.42545495,  1.1969253 ,  0.84640923,  1.79356692, -1.83408336]])

In [25]:
# DO NOT CHANGE

y5 = np.array([[ 1.46994671, -0.05535155,  0.1809549 ,  0.09982112,  0.72415382],
       [-0.43302509,  0.28419608,  1.43481809,  0.19801696,  0.22396864],
       [-1.21475138,  0.60960865,  0.90861035,  0.25103477,  0.57198302],
       [-1.21089702,  0.17419828,  0.04772397, -0.97154458, -0.74168603],
       [-2.05435996,  0.00357587, -0.31438553, -0.52754128,  0.35035861]])
y5

array([[ 1.46994671, -0.05535155,  0.1809549 ,  0.09982112,  0.72415382],
       [-0.43302509,  0.28419608,  1.43481809,  0.19801696,  0.22396864],
       [-1.21475138,  0.60960865,  0.90861035,  0.25103477,  0.57198302],
       [-1.21089702,  0.17419828,  0.04772397, -0.97154458, -0.74168603],
       [-2.05435996,  0.00357587, -0.31438553, -0.52754128,  0.35035861]])

In [26]:
# YOUR CHANGES HERE

p5 = 3*x5 + 2*y5

In [27]:
p5

array([[ 2.20820311, -0.91561093, -2.5991328 ,  3.89788561,  1.47303247],
       [ 0.14450468,  2.08155685,  4.39824121,  3.58502663,  1.8745355 ],
       [-2.63889232,  3.88038011,  2.01045394, -0.59231609,  7.5740227 ],
       [-1.79852355,  3.24488663,  2.78223246,  2.13738862, -0.83551138],
       [ 0.16764493,  3.59792764,  1.91045663,  4.3256182 , -4.80153286]])

### Problem 6

Set `p6` to the result of the matrix multiplication
$\begin{bmatrix}
1 & 3 \\
2 & 0 \\
\end{bmatrix}
\begin{bmatrix}
0 & 3 \\
2 & -1 \\
\end{bmatrix}$


In [29]:
# YOUR CHANGES HERE

arr_1 = np.array([[1, 3],
                 [2, 0]])

arr_2 = np.array([[0, 3],
                 [2, -1]])

p6 = arr_1 @ arr_2

In [30]:
p6

array([[6, 0],
       [0, 6]])

### Problem 7

Set `p7` to be the result of multiplying the matrices in `x7` and `y7`.

Hint: use NumPy's matrix multiplication functionality.

In [31]:
# DO NOT CHANGE

x7 = np.array([[ 1.12510969, -0.68403506,  1.106613  ,  0.26977997,  1.31003595],
       [-2.46789639, -0.631568  , -0.40459478, -0.44276999,  0.35342956],
       [ 0.08847366,  1.04391453, -2.06768109, -1.59304958, -1.45124381],
       [-0.31574675,  0.47213461,  0.01544427, -1.00203016,  0.30260759],
       [-0.18144407,  0.55210749, -0.96200836,  0.77615041, -0.82085057]])
x7

array([[ 1.12510969, -0.68403506,  1.106613  ,  0.26977997,  1.31003595],
       [-2.46789639, -0.631568  , -0.40459478, -0.44276999,  0.35342956],
       [ 0.08847366,  1.04391453, -2.06768109, -1.59304958, -1.45124381],
       [-0.31574675,  0.47213461,  0.01544427, -1.00203016,  0.30260759],
       [-0.18144407,  0.55210749, -0.96200836,  0.77615041, -0.82085057]])

In [32]:
# DO NOT CHANGE

y7 = np.array([[-0.53240175,  0.59279203,  0.19610132,  0.31489693,  1.31591487],
       [ 0.90107926,  0.01106459,  0.4695847 ,  0.21402271,  0.48587671],
       [-0.31841096,  1.08388531,  0.05264241, -0.3044392 ,  1.34193777],
       [-0.56276555, -0.71220132, -0.99487118,  0.66883629,  0.49585603],
       [-0.01016394, -2.2580422 , -2.72960502, -0.33287333, -0.34948483]])
y7

array([[-0.53240175,  0.59279203,  0.19610132,  0.31489693,  1.31591487],
       [ 0.90107926,  0.01106459,  0.4695847 ,  0.21402271,  0.48587671],
       [-0.31841096,  1.08388531,  0.05264241, -0.3044392 ,  1.34193777],
       [-0.56276555, -0.71220132, -0.99487118,  0.66883629,  0.49585603],
       [-0.01016394, -2.2580422 , -2.72960502, -0.33287333, -0.34948483]])

In [33]:
# YOUR CHANGES HERE

p7 = x7 @ y7

In [34]:
p7

array([[-1.73287588, -1.29142505, -3.88659915, -0.38463922,  2.30913198],
       [ 1.1192304 , -2.39118918, -1.32605525, -1.20291629, -4.4404152 ],
       [ 2.4631823 ,  2.23440959,  5.94490988,  0.29835567, -2.43379733],
       [ 1.14944957, -0.13486187,  0.33149359, -0.77400613, -0.76799084],
       [ 0.47196012,  0.1565834 ,  1.64146553,  1.14625724, -0.58973045]])

### Problem 8

Set `p8` to the result of the matrix-vector multiplication
$\begin{bmatrix}
1 & 3 \\
4 & 0 \\
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
\end{bmatrix}$.

In [35]:
# YOUR CHANGES HERE

arr_1 = np.array([[1, 3],
                  [4, 0]])

arr_2 = np.array([[1],
                  [2]])

p8 = arr_1 @ arr_2

In [36]:
p8

array([[7],
       [4]])

### Problem 9

Set `p9` to be the result of matrix multiplication on `components9` and `materials9`.


Hint: even though these are data frames, you can still multiply them with the @ operator as if they were NumPy arrays, but the indexes and column names will be preserved.

In [37]:
# DO NOT CHANGE

components9 = pd.DataFrame(index=["robot", "cart", "vacuum"],
                           data={"gears": [4, 1, 2], "wires": [2, 1, 3], "leds": [5, 2, 1]})
components9

gears  wires  leds
robot       4      2     5
cart        1      1     2
vacuum      2      3     1

In [38]:
# DO NOT CHANGE

materials9 = pd.DataFrame(index=["gears", "wires", "leds"],
                          data={"metal": [1, 0.2, 0.01], "plastic": [1, 0.4, 0.02]})
materials9

metal  plastic
gears   1.00     1.00
wires   0.20     0.40
leds    0.01     0.02

In [39]:
# YOUR CHANGES HERE

p9 = components9 @ materials9

In [40]:
p9

metal  plastic
robot    4.45     4.90
cart     1.22     1.44
vacuum   2.61     3.22

### Problem 10

The variable `q10` has the transition probabilities for a trivial weather model based on Markov chains.
Set `p10` to be the steady state probabilities of each weather condition under this model.

In [41]:
# DO NOT CHANGE

q10 = pd.DataFrame(index=["sun", "cloudy", "rainy"],
                   data={"sun": [0.8, 0.1, 0.1],
                         "cloudy": [0.1, 0.5, 0.2],
                         "rainy": [0.1, 0.4, 0.7]})
q10

sun  cloudy  rainy
sun     0.8     0.1    0.1
cloudy  0.1     0.5    0.4
rainy   0.1     0.2    0.7

In [48]:
# YOUR CHANGES HERE

def steady_state_linear(P):
    n = P.shape[0]
    A = P.T - np.eye(n)
    A[-1] = np.ones(n)
    b = np.zeros(n)
    b[-1] = 1
    return np.linalg.solve(A, b)

steady_state_prob = steady_state_linear(q10.values)

p10 = steady_state_prob

In [49]:
p10

array([0.33333333, 0.23809524, 0.42857143])

### Problem 11

The vector `v11` below is an eigenvector of the matrix `q11`.
Set `p11` to the eigenvalue corresponding to `v11`.

In [50]:
# DO NOT CHANGE

q11 = np.array([[1, 2], [2, 4]])
q11

array([[1, 2],
       [2, 4]])

In [51]:
# DO NOT CHANGE

v11 = np.array([[1], [2]])
v11

array([[1],
       [2]])

In [52]:
# DO NOT CHANGE

q11 @ v11

array([[ 5],
       [10]])

In [60]:
# YOUR CHANGES HERE

result = q11 @ v11

p11 = result[0, 0] / v11[0, 0]

In [61]:
p11

np.float64(5.0)

### Problem 12

Set `p12` to the reduced row echelon form of `q12`.


Hint: just do this on paper instead of looking for a NumPy function.

In [67]:
# DO NOT CHANGE

q12 = np.array([[1, 0, 1],
                [0, 1, 3],
                [0, 0, 2]])
q12

array([[1, 0, 1],
       [0, 1, 3],
       [0, 0, 2]])

In [66]:
# YOUR CHANGES HERE

n = q12.shape[0]
col = 0

for i in range(n):
    if col >= q12.shape[1]:
        break

    if q12[i, col] != 0:
        q12[i] = q12[i] / q12[i, col]

    for j in range(n):
        if i != j and q12[j, col] != 0:
            q12[j] = q12[j] - q12[j, col] * q12[i]

    col += 1

p12 = q12
print(p12)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [68]:
p12

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Problem 13

Set `p13` to the reduced row echelon form of `q13`.

Hint: just do this on paper instead of looking for a NumPy function.

In [5]:
# DO NOT CHANGE

q13 = np.array([[3, 0, 1], [6, 3, 2], [0, 2, 0]])
q13

array([[3, 0, 1],
       [6, 3, 2],
       [0, 2, 0]])

In [6]:
# YOUR CHANGES HERE

A = q13.astype(float).copy()
n = A.shape[0]
col = 0

for i in range(n):
    if col >= A.shape[1]:
        break
    if A[i, col] != 0:
        A[i] = A[i] / A[i, col]
    for j in range(n):
        if i != j and A[j, col] != 0:
            A[j] = A[j] - A[j, col] * A[i]
    col += 1

p13 = A

In [7]:
p13

array([[1.        , 0.        , 0.33333333],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        ]])

### Problem 14

Set `p14` to be the rank of `q14`.


In [72]:
# DO NOT CHANGE

q14 = np.array([[0, 2, 0], [1, 0, 3], [2, 2, 6]])
q14

array([[0, 2, 0],
       [1, 0, 3],
       [2, 2, 6]])

In [74]:
# YOUR CHANGES HERE

p14 = np.linalg.matrix_rank(q14)

In [75]:
p14

np.int64(2)

### Problem 15

Set `p15` to be $\mathbf{Q}^3$ where $\mathbf{Q}$ is in `q15`.

In [76]:
# DO NOT CHANGE

q15 = np.array([[1.0, 0.0, 0.1], [0.0, 1.0, 0.1], [0.1, 0.0, 1.0]])
q15

array([[1. , 0. , 0.1],
       [0. , 1. , 0.1],
       [0.1, 0. , 1. ]])

In [80]:
# YOUR CHANGES HERE

p15 = np.linalg.matrix_power(q15, 3)

In [81]:
p15

array([[1.03 , 0.   , 0.301],
       [0.03 , 1.   , 0.301],
       [0.301, 0.   , 1.03 ]])

### Problem 16

Given the transition matrix for a Markov chain in `q16`, what is the conditional probability of being in state 2 at time step 10 after being in state 0 at time step 0.

Hint: NumPy has a function [`matrix_power`](https://numpy.org/devdocs/reference/generated/numpy.linalg.matrix_power.html) which will make this easier.

In [82]:
# DO NOT CHANGE

q16 = np.array([[0.1, 0.3, 0.6], [0.2, 0.5, 0.3], [1.0, 0.0, 0.0]])
q16

array([[0.1, 0.3, 0.6],
       [0.2, 0.5, 0.3],
       [1. , 0. , 0. ]])

In [87]:
# YOUR CHANGES HERE

n_steps = 10
p_10 = np.linalg.matrix_power(q16, n_steps)

initial_state_vector = np.array([1, 0, 0])

final_state_vector = initial_state_vector @ p_10

p16 = final_state_vector[2]

In [88]:
p16

np.float64(0.3172631450999999)

### Problem 17

Set `p17` to the results of Gaussian elimination on `q17`.

In [8]:
# DO NOT CHANGE

q17 = np.array([[0.0, 1.0, 0.0, 2.0], [1.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 2.0], [0.0, 0.0, 0.0, 0.1]])
q17

array([[0. , 1. , 0. , 2. ],
       [1. , 0. , 1. , 0. ],
       [1. , 1. , 1. , 2. ],
       [0. , 0. , 0. , 0.1]])

In [11]:
# YOUR CHANGES HERE

n = q17.shape[0]

A = q17.copy()
r, nrows, ncols = 0, A.shape[0], A.shape[1]

for c in range(ncols):
    max_row = r + np.argmax(np.abs(A[r:, c]))
    if A[max_row, c] == 0:
        continue
    A[[r, max_row]] = A[[max_row, r]]

    for j in range(r + 1, nrows):
        factor = A[j, c] / A[r, c]
        A[j] = A[j] - factor * A[r]

    r += 1
    if r == nrows:
        break

A = np.where(np.isclose(A, 0.0, atol=1e-12), 0.0, A)

print("\nAfter Gaussian elimination:")
print(A)
# Output:
# [[1.  0.  1.  0. ]
#  [0.  1.  0.  2. ]
#  [0.  0.  0.  0.1]
#  [0.  0.  0.  0. ]]

p17 = A


After Gaussian elimination:
[[1.  0.  1.  0. ]
 [0.  1.  0.  2. ]
 [0.  0.  0.  0.1]
 [0.  0.  0.  0. ]]


In [12]:
p17

array([[1. , 0. , 1. , 0. ],
       [0. , 1. , 0. , 2. ],
       [0. , 0. , 0. , 0.1],
       [0. , 0. , 0. , 0. ]])

### Problem 18

Set `p18` to be a row vector of two numbers that are coefficients to show that the third row of `q18` is linearly dependent on the first two rows of `q18`.

Hint: do this by hand instead of in code, and use the tracking trick.

In [99]:
# DO NOT CHANGE

q18 = np.array([[0.2, 0.5, 0.3], [0.1, 0.1, 0.1], [0.4, 0.7, 0.5]])
q18

array([[0.2, 0.5, 0.3],
       [0.1, 0.1, 0.1],
       [0.4, 0.7, 0.5]])

In [106]:
row_1 = np.array([0.2, 0.5, 0.3])
row_2 = np.array([0.1, 0.1, 0.1])
row_3 = np.array([0.4, 0.7, 0.5])

A = np.column_stack((row_1, row_2))
results = np.linalg.lstsq(A, row_3, rcond=None)
coefficients = results[0]
a, b = coefficients[0], coefficients[1]
print(a)
print(b)

p18 = np.array([a, b])

0.9999999999999999
2.000000000000003


In [107]:
p18

array([1., 2.])

In [108]:
# should match the last row of q18

p18 @ q18[:2,:] if p18 is not ... else None

array([0.4, 0.7, 0.5])

### Problem 19

Set `p19` to be the inverse of `q19`.


Hint: NumPy has a function for this in its "linalg" sub-module.

In [83]:
# DO NOT CHANGE

q19 = np.array([[1, 0.2, 0.4], [0.3, 1.2, 1.5], [2.0, 0.1, 0.2]])
q19

array([[1. , 0.2, 0.4],
       [0.3, 1.2, 1.5],
       [2. , 0.1, 0.2]])

In [84]:
# YOUR CHANGES HERE

p19 = np.linalg.inv(q19)

In [85]:
p19

array([[-3.33333333e-01,  1.72701359e-17,  6.66666667e-01],
       [-1.08888889e+01,  2.22222222e+00,  5.11111111e+00],
       [ 8.77777778e+00, -1.11111111e+00, -4.22222222e+00]])

In [86]:
# try multiplying them together if p19 was assigned. should give an identity matrix.

q19 @ p19 if p19 is not ... else None


array([[ 1.00000000e+00, -6.90805438e-17, -4.93432455e-18],
       [ 8.88178420e-16,  1.00000000e+00, -1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

### Problem 20

The matrix in `q20` represents a rotation transformation.
Set `p20` to the angle in radians of that rotation.


Hint: such a matrix is usually called a "rotation matrix".

In [113]:
# DO NOT CHANGE

q20 = np.array([[0.7402293552151602, -0.672354446462391], [0.672354446462391, 0.7402293552151602]])
q20

array([[ 0.74022936, -0.67235445],
       [ 0.67235445,  0.74022936]])

In [121]:
# YOUR CHANGES HERE

a = q20[0, 0]
b = q20[1, 0]

p20 = np.arctan2(b, a)

In [122]:
p20

np.float64(0.7373849099999998)

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE

Problem 11
* I wasn’t sure how to find the eigenvalue when given an eigenvector. I learned we can use the division method instead of np.linalg.eig.
* https://chatgpt.com/share/68fe45e9-ad64-800d-962c-ea3927605d44

Problem 12
* I didn't know the manual calculation for finding reduced row echelon form.
* https://chatgpt.com/share/68fe99b3-3224-800d-88d2-e28e8842d980

Problem 13
* I knew I was close, but didn't understand why it wasn't the correct value. I learned that to prevent truncation we need to change to a float which makes sense.
* https://chatgpt.com/share/690635a9-40cc-800d-af3f-84d771cb13ce

Problem 17
* I knew I was close, but didn't understand that I needed a separate pivot row. After learning about why, it made more sense.
* https://chatgpt.com/share/69063803-8efc-800d-bce7-91e1ff00e83a

Problem 20
* I didn't know how to find the angle in radians of the rotation given a rotation matrix.
* https://chatgpt.com/share/68ff7dad-1c70-800d-b113-6529044ffa87